---
title: "Progress Track"
output: html_document
---


## The 'Progress' table:

| WeekNo. | Q | A | Things investigated |
| ---: | ---------------------: | ----------------------------------: | -----------------: |
| 1 | Is it possible to link a plot to a table using the following: plotly, rbokeh, highcharter? | Possible, but not in a standalone sense. Requires API expertise, or another tool to link up. | Plotly, highcharter, rbokeh/bokeh,  crosstalk. |
| 2 | What about linking a plot to a table using ggvis, rvega and Shiny? Is it possible to return values selected? | Yes for ggvis. No to rVega. | Introduction to Shiny, ggvis, rVega is not official for the Vega library (use ggvis instead). |
| 3 | What are the limits to Shiny's interactive functions? | Only works for base and ggplot2 (png rendered) via mapping. Not possible to impose on lattice. ggvis has its own functions for achieving the same effect. Works best on scatterplots (including facetted plots). Requires thought for use on other plots (bar plots, histograms) and may not necessarily work. | Shiny's brushedPoints() and interactive functions, rendering ggvis in Shiny, ggvis' way of achieving interaction |
| 4 | Investigate the following in more detail: Shiny + Plotly, Shiny + ggvis, Crosstalk and capabilities of facetting | Plotly can do facetting either using ggplot2 -> ggplotly, or make each separate plot and combine using subplot(). Limitations to using "plotly_selected" - only works on scatterplots + facetted scatters. Not available for ggvis. | Linking Shiny + ggvis, Plotly + Shiny, Crosstalk + Plotly | 
|5-6| Challenges: box plot, array of plots, trendline | **Trendline:** easily achievable with any of the following (Plotly, ggvis, rbokeh, iNZightPlots...) + Shiny - however, still rerendering the entire plot every time. Plotly does not have statistical curves or functions. Another way: use ggplot2 -> ggplotly(). iPlots via code (not through UI). **Boxplot:** impossible for any. In theory, it is possible (since they are all JS libraries) but requires expertise and knowledge of API. Achievable using iNZightPlots/gridSVG/custom JS. **Array of plots:** Shiny + Crosstalk + Plotly/D3scatter, however can't get to link to pop-up window or to retain selection. ggvis + Shiny requires linking up of plots to be done individually + does not clear brushing after use. | Summary tables, ggvis + interactivity, examples of Crosstalk + Shiny + Plotly, confirming Plotly + Crosstalk communication, Plotly API, iPlots, rggobi, Co-ordinating multiple views using Shiny, trelliscope/trelliscopeJS for trellis displays + large datasets, JavaScript in Shiny via making an HTMLWidget, shinyJS, incorporating events in Shiny |
|7-9| Think about how you'd like to express a solution to the three challenges without thinking about existing tools + can you do the trendline challenge without rerendering entire plot? | A main idea of creating a package that allows interactive functions to be added to static plots. | Rendering SVG in Shiny, sending messages/data between JS <-> Shiny, Introducing DOM, challenge summary, Shiny's reactive programming model, HTMLWidgets, Mondrian, ggplot2 + ggiraph |
|10 | ?? | ?? | ??|
