---
title: "array-challenge"
output: html_document
runtime: shiny
---
## Objective: A scatterplot matrix that's linked, with single view capabilities

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(ggvis)
library(plotly)
library(crosstalk)
library(GGally)
library(d3scatter)
```

#### A simple scatterplot matrix:
```{r}
pairs(iris[, 1:4])
```

#### A linked scatterplot matrix using GGally

```{r}
shared_iris <- SharedData$new(iris)
ggpairs(shared_iris, aes(color = Species)) 
```

#### Crosstalk + Plotly + Shiny:

```{r, echo = FALSE}
shinyApp(
  ui <- fluidPage(
    fluidRow(
      plotlyOutput('plotMatrix')
    ),
    fluidRow(
      column(3,actionButton("show", "Zoom into plot5")),
      selectInput('view', "View plot", c("0" = "0", "1" = "1", "2" = "2"), "0")
    )
  ),
  
  server <- function(input, output, session) {
    
    #defined shared object/dataset:
    shared_iris <- SharedData$new(iris)
    
    observeEvent(input$show, {
      showModal(modalDialog(
        output$sl1 <- renderPlotly({
          plot_ly(data = shared_iris, x = ~Sepal.Length, y = ~Sepal.Width, color = ~Species, type = "scatter", mode = "markers")
        })
      ))
    })
    
    observeEvent(input$view, {
      
      if (input$view == "1") {
        showModal(modalDialog(
          output$sw1 <- renderPlotly({
            plot_ly(data = shared_iris, x = ~Sepal.Width, y = ~Sepal.Width, color = ~Species, type = "scatter", mode = "markers")
          })
        )
       )
      } else if (input$view == "2") {
        showModal(modalDialog(
          output$sw2 <- renderPlotly({
            plot_ly(data = shared_iris, x = ~Sepal.Width, y = ~Petal.Length, color = ~Species, type = "scatter", mode = "markers")
          })
        ) 
        )
      } else {
        return()
      }
      
    })
    
    output$plotMatrix <- renderPlotly({
      #SepalLength:
      sl1 <- plot_ly(data = shared_iris, x = ~Sepal.Length, y = ~Sepal.Width,color = ~Species, type = "scatter", mode = "markers")
      sl2 <- plot_ly(data = shared_iris, x = ~Sepal.Length, y = ~Petal.Length,color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      sl3 <- plot_ly(data = shared_iris, x = ~Sepal.Length, y = ~Petal.Width, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      sl4 <- plot_ly(data = shared_iris, x = ~Sepal.Length, y = ~Sepal.Length,color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      
      #Sepal.Width:
      sw1 <- plot_ly(data = shared_iris, x = ~Sepal.Width, y = ~Sepal.Width, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      sw2 <- plot_ly(data = shared_iris, x = ~Sepal.Width, y = ~Petal.Length, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      sw3 <- plot_ly(data = shared_iris, x = ~Sepal.Width, y = ~Petal.Width, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      sw4 <- plot_ly(data = shared_iris, x = ~Sepal.Width, y = ~Sepal.Length, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      
      #Petal.Length:
      pl1 <- plot_ly(data = shared_iris, x = ~Petal.Length, y = ~Sepal.Width, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      pl2 <- plot_ly(data = shared_iris, x = ~Petal.Length, y = ~Petal.Length, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      pl3 <- plot_ly(data = shared_iris, x = ~Petal.Length, y = ~Petal.Width, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      pl4 <- plot_ly(data = shared_iris, x = ~Petal.Length, y = ~Sepal.Length, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      
      #Petal.Width:
      pw1 <- plot_ly(data = shared_iris, x = ~Petal.Width, y = ~Sepal.Width, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      pw2 <- plot_ly(data = shared_iris, x = ~Petal.Width, y = ~Petal.Length, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      pw3 <- plot_ly(data = shared_iris, x = ~Petal.Width, y = ~Petal.Width, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      pw4 <- plot_ly(data = shared_iris, x = ~Petal.Width, y = ~Sepal.Length, color = ~Species, type = "scatter", mode = "markers", showlegend = FALSE)
      
      #put it altogether as a single plotly object
      subplot(sw1, sw2, sw3, sw4, pl1, pl2, pl3, pl4, pw1, pw2, pw3, pw4, sl1, sl2, sl3, sl4, nrows = 4)
      
    })
  }
)
```

#### Crosstalk + d3scatter (no in-plot interaction) + Shiny (1/2 matrix):

```{r, echo = FALSE}
shinyApp(
  ui <- fluidPage(
    fluidRow(
      column(3, d3scatterOutput('sw1')), 
      column(3, d3scatterOutput('sw2')), 
      column(3, d3scatterOutput('sw3')), 
      column(3, d3scatterOutput('sw4'))
    ),
    fluidRow(
      column(3, d3scatterOutput('sl1')), 
      column(3, d3scatterOutput('sl2')), 
      column(3, d3scatterOutput('sl3')), 
      column(3, d3scatterOutput('sl4'))
    ),
    fluidRow(
      ##would modals work?
      column(3,actionButton("show", "Zoom into plot5")),
      column(3, actionButton("link", "Link to Wikipedia"))
  )
  ),
  
  server <- function(input, output, session) {
    shared_iris <- SharedData$new(iris)
    
    observeEvent(input$show, {
      showModal(modalDialog(
        output$sl1 <- renderD3scatter({
          d3scatter(data = shared_iris, x = ~Sepal.Length, y = ~Sepal.Width, color = ~Species)
        })
      ))
    })
    
    observeEvent(input$link, {
      showModal(urlModal('https://en.wikipedia.org/wiki/Iris_flower_data_set', title = "About the iris dataset")
      )
    })
    
    output$sl1 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Length, y = ~Sepal.Width, color = ~Species)
    })
    
    output$sl2 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Length, y = ~Petal.Length, color = ~Species)
    })
    
    output$sl3 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Length, y = ~Petal.Width, color = ~Species)
    })
    
    output$sl4 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Length, y = ~Sepal.Length, color = ~Species)
    })
    
    output$sw1 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Width, y = ~Sepal.Width, color = ~Species)
    })
    
    output$sw2 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Width, y = ~Petal.Length, color = ~Species)
    })
    
    output$sw3 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Width, y = ~Petal.Width, color = ~Species)
    })
    
    output$sw4 <- renderD3scatter({
      d3scatter(data = shared_iris, x = ~Sepal.Width, y = ~Sepal.Length, color = ~Species)
    })
    
  }
  
)
```

#### ggvis + Shiny: - SO ggvis doesn't work on markdown.

```{r, echo = FALSE}
shinyApp(
  ui <- fluidPage(
    fluidRow(
      column(6, ggvisOutput('plot1')),
      column(6, ggvisOutput('plot2'))
    ),
    fluidRow(
      column(6, ggvisOutput('plot3')),
      column(6, ggvisOutput('plot4'))
    ),
    fluidRow(
      ## add a modal and see what happens?? Could I link them back to the other 4 plots?
      column(12, actionButton("show", "Show plot1")),
      column(12, ggvisOutput('plot5'))
    )
    
  ),

server <- function(input, output, session) {

   #set an id:
  iris$id <- seq_len(nrow(iris))
  
  #linked brush points
  lb <- linked_brush(keys = iris$id, "red")
  
  ## in this case: plot1 and plot2 can do brushing, but all plots are linked via a key.
  ## If brushing is done on plot1, then plot2, 3, 4 should show the points that are selected.
  ## Could use a little refining if you could clear the brushing on one plot after brushing on another.
  ## Just simplifying it to a single row (since it appears that ggvis plots don't fit/adjust in the bootstrap columns)
  ## seems like I can't just add ggvis output to a modal...
  
  observeEvent(input$show, {
    iris %>%
        ggvis(~Sepal.Length, ~Sepal.Width, key := ~id) %>%
        #then you layer on the points that are actually highlighted
        layer_points(fill := lb$fill, fill.brush := "red") %>%
        lb$input() %>%
        bind_shiny('plot5')
  })
  
  iris %>%
    ggvis(~Sepal.Length, ~Sepal.Width, key := ~id) %>%
    #then you layer on the points that are actually highlighted
    layer_points(fill := lb$fill, fill.brush := "red") %>%
    lb$input() %>%
  bind_shiny('plot1')
  
  #plot2:
  iris %>%
    ggvis(~Sepal.Length, ~Petal.Width, key := ~id) %>%
    layer_points(fill := lb$fill, fill.brush := "red") %>%
    lb$input() %>%
  bind_shiny('plot2')
  
  #store whatever's selected as a reactive object for other plots to follow:
  selected <- lb$selected
  iris_selected <- reactive({
    iris[selected(), ]
    })
  
  #plot3: controlled by whatever's been highlighted
  iris %>%
    ggvis(~Sepal.Length, ~Petal.Length, key := ~id) %>%
    layer_points() %>%
    add_data(iris_selected) %>% ## add on an additional layer to show which are 'linked'
    layer_points(fill := "red") %>%
    bind_shiny('plot3')
  
  #plot4:
  iris %>%
    ggvis(~Sepal.Length, ~Sepal.Length, key := ~id) %>%
    layer_points() %>%
    add_data(iris_selected) %>%
    layer_points(fill := "red") %>%
    bind_shiny('plot4')
  
  }
)

```
