---
title: "trendline-challenge"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggvis)
library(knitr)
library(plotly)
library(iNZightPlots)
```

Just testing out ggvis + Shiny apps with RMarkdown and knitr.

### Example 1: using ggvis alone

```{r}
income <- read.csv('~/Desktop/datasets/nzincome.csv', header = TRUE)

ggvis(cocaine, ~weight, ~price) %>%
  layer_points() %>%
  layer_smooths(stroke := "red", span = input_slider(0.5, 1, value = 1, label = "Span of loess curve (red)")) %>%
  layer_model_predictions(stroke := "blue", model = input_select(c("Loess" = "loess", "Linear Model" = "lm", "RLM" = "MASS::rlm"), label = "Select a model"),
                          se = TRUE)

```

### Example 2: using Plotly graphs + Shiny

```{r}

shinyApp(
    ui = fluidPage(
         titlePanel("Trendline challenge: Plotly + Shiny"),
         sidebarLayout(
            sidebarPanel(
               selectInput("model", "Model", c("Linear" = "lm", "Loess" = "loess", "RLM" = "rlm")),
               numericInput("obs", "Observations:", 3380, min = 0, max = 3380),
               sliderInput("span", "Span for loess", min = 0.5, max = 1, value = 0.75)
               ), 
            mainPanel(
              plotlyOutput("plot")
                ), 
            position = c("left", "right"),
            fluid = TRUE)
       ),
     
       server = function(input, output) {
           
             output$plot <- renderPlotly({
                 
                 if (input$obs == nrow(cocaine)) {
                      cocaine <- cocaine
                     } else {
                       cocaine <- cocaine[1:input$obs, ]
                     }
                 
                   plot <- plot_ly(cocaine, x = ~weight, y = ~price, mode = "markers", type = "scatter")
                   
                    #run condition for model lines:
                     if (input$model == "loess") { 
                         modelLine <- loess(price ~ weight, data = cocaine, span = 0.75, se = TRUE)
                      } else if (input$model == "MASS::RLM") {
                           modelLine <- mass::rlm(price ~weight, data = cocaine)
                         } else {
                             modelLine <- lm(price ~ weight, data = cocaine)
                           }
                   
                     #add trendline
                    add_lines(plot,y = ~fitted(modelLine), line = list(color = "red"))
                  # you could add standard errors via add_ribbons().
                    
                  })
           }
   )

```

### Using ggplotly() + Shiny:

```{r}

total.obs <- nrow(cocaine)

shinyApp(
  
ui = fluidPage(
  titlePanel("Trendline challenge: using ggplot2 + ggplotly + Shiny"),
  sidebarLayout(
    sidebarPanel(
      selectInput("model", "Model", c("GAM" = "gam", "Linear" = "lm", "Loess" = "loess", "GLM" = "glm")),
      numericInput("obs", "Observations:", total.obs, min = 0, max = total.obs),
      sliderInput("span", "Span for loess:", min = 0.5, max = 1, value = 0.75), 
      verbatimTextOutput("summary")
      
    ), mainPanel(
      plotlyOutput("plot")
    )
    , position = c("left", "right"),
    fluid = TRUE)
),

server = function(input, output) {
  
  output$plot <- renderPlotly({
    
    if (input$obs == total.obs) {
      cocaine <- cocaine
    } else {
      cocaine <- cocaine[1:input$obs, ]
    }
    
    #creating the plot:
    p <- ggplot(cocaine, aes(weight, price)) + geom_point() 
    p <- p + stat_smooth(method = input$model, span = input$span, se = TRUE)
    ggplotly(p)
    
  })
    
  output$summary <- renderPrint({
    
    if (input$obs == total.obs) {
      cocaine <- cocaine
    } else {
      cocaine <- cocaine[1:input$obs, ]
    } #might make this reactive to prevent repeats
    
    #compute summary for model:
    if (input$model == "lm") {
      lm(price ~ weight, data = cocaine)
    } else if (input$model == "loess") {
      loess(price ~ weight, data = cocaine)
    } else if (input$model == "glm") {
      glm(price ~ weight, data = cocaine)
    } else {
      mgcv::gam(price ~ weight, data = cocaine)
    }
  })
   
  
}
)

```

## iNZightPlots + Shiny?

```{r}

shinyApp (
  ui = fluidPage(
    titlePanel("Trendline challenge: iNZightPlots + Shiny"),
    sidebarLayout(
      sidebarPanel( #things on the side...
        selectInput("trend", "Trend", c("Linear" = "linear", "Quadratic" = "quadratic", "Cubic" = "cubic")),
        numericInput("obs", "Observations:", total.obs, min = 0, max = total.obs),
        sliderInput("smooth", "Smoothness", min = 0.5, max = 1, value = 0.75), 
        sliderInput("lwd", "Line width", min = 0.1, max = 5, value = 1)
        
      ), mainPanel(
        plotOutput("plot"),
        verbatimTextOutput("summary")
      )
      , position = c("left", "right"),
      fluid = TRUE)
  ),
  
  server = function(input, output) {
    
    output$plot <- renderPlot({
      
      if (input$obs == total.obs) {
        cocaine <- cocaine
      } else {
        cocaine <- cocaine[1:input$obs, ]
      }
      
      #creating the iNZightPlot:
      iNZightPlots::iNZightPlot(weight, price, data = cocaine, trend = input$trend, smooth = input$smooth, lwd = input$lwd)
      
    })
    
    output$summary <- renderPrint({
      
      if (input$obs == total.obs) {
        cocaine <- cocaine
      } else {
        cocaine <- cocaine[1:input$obs, ]
      } #might make this reactive to prevent repeats
      
      #compute summary for model:
      iNZightPlots::getPlotSummary(weight, price, data = cocaine, trend = input$trend, smooth = input$smooth, lwd = input$lwd, summary.type = "inference")
      
    })
  }
)

```
