---
output: pdf_document
---

# Discussion

The `interactr` package provides a way of generating simple interactive R plots that can be viewed in a web browser. It is advantageous in the sense that we can easily define and customise interactions with flexibility. It can also achieve unidirectional linking between a variety of plots.

*TODO: incorporate these*
- WARNING from Paul about DOM:
> "DOM does nothing to help with synchronising cascades of updates (OR infinite loops of updates)"

- requires that units that are converted to 'native' via grid should represent the data. (for ggplot2, this doesn't hold and requires a different conversion scale. In cases like this, there should be an alternative based upon where it gets data from:  use ```ggplot_build()```)
- assumes no missing values and that plots generated via gridSVG should be in the order of the data frame. (ie point order should match with indices of the df.) In cases where data taken in is rearranged and sorted (like iNZightPlots), this causes the 'indexes' of the points to differ to the original dataframe.
-  assumes that most grid objects represent a single object in SVG (which sometimes is not the case - see iNZightPlot boxplot version)

## Limitations

Firstly, there are limitations that arise from using the gridSVG and DOM packages. With gridSVG, one of the major limitations is that only grid objects can be converted into SVG. This limits us to plots that must be drawn in R before being sent to the browser. A further limitation is that gridSVG is relatively slow when we plot many points or objects at once. This can compromise the efficiency when we need to send the plot to the browser. Hence, we are limited to small data sets.

As `interactr` is mainly built upon the `DOM` package, many of its limitations highlighted in Chapter 3 are carried forward. This includes the shareability and accessibility of these plots, where they are generated for a single user in a single session only. Furthermore, because the `DOM` package is still under development, it cannot be used for production purposes yet. Just as how shiny applications would require a shiny server to be hosted on the web, DOM would require something similar to allow for shareability. This has not been done before, but it could be experimented with in the future. Furthermore, because the underlying system consists of requests being sent between R and the web browser, this can be relatively slower when compared to plots that are driven fully by JavaScript.

There are further limitations within the package. The user must call `listElements` before sending the plot to the browser as it prints the plot and a correct list of elements that make up the plot. This is crucial for plotting systems that do not have a consistent naming scheme. If we reprint the plot, the tags will constantly change which may cause a mismatch between element matching between the plot on the web and the plot in R. A further limitation is that the user will need to deduce which element is on the plot as the naming for these objects in `grid` may not be clear. If it is a plot that is made directly from grid where the user has named everything clearly, then this is not a problem. However, if it is based upon a defined plotting system like ggplot2, then there is a need for deducing which elements correspond to which part of the plot.

Another limitation is the number of interactions that can be attached. So far, the examples expressed in Chapter 4.3 require a single element to be controlled. We can attach many interactions and events to a single element at a time, but not many elements to many different interactions at once. There is a need for a more flexible system when dealing with multiple interactions for achieving more complex interactions. Furthermore, only one kind of interaction can be expressed for a single event. This means that the function created by the user must be fully defined in a single function rather than multiple functions. For example, if a hover requires both adding a tooltip and to turn the element red, then this would need to be written as a single function as we can only attach one to each event. Code must also be written in a certain order to work. Plots in R must be drawn to a graphics device before being sent to the browser, while a new web page must be set up before we can start adding elements and interactions to the page.
In cases of dealing with multiple plots, one of the disadvantages is that we lose information about the previous plot in R. This means that the user is required to identify what kind of information they need to extract before they move onto the next plot. This is demonstrated in the example of linking box plot to other plots together - before the user can move onto the scatter plot, the range of the box and viewports were stored in order to be used in the defined function. This means that we cannot jump back and forth between plots. A possible solution for this is to be able to store the information about each plot that is sent to the web browser that can be retrievable by the user if needed.
	
## Comparison to existing tools

In most of the existing tools discussed in Chapters 2, they all rely on a JavaScript library to render their plots. These are not R plots. `interactr`'s main selling point is the ability to replicate plots or objects drawn in R and to easily achieve on-plot and off-plot interactivity. `shiny` can do this but you cannot easily attach specific interactions as the plot is rendered as a png. Furthermore, many of these existing tools rely on the `shiny` framework. One of the major disadvantages that `shiny` possesses is a tendency to recompute and redraw entire plots whenever an input changes. In `interactr`, only part of the plot that the user specifically targets is modified, and more on-plot interactions can be achieved. Furthermore, the `interactr` package provides a possible way of linking different types of plots together, whereas existing tools, specifically crosstalk, have focused on linked brushing between scatter plots. To put in perspective, the simple example of linking box plots to other kinds of plots together (Figure 4.2) is an interaction that is difficult to achieve without expert knowledge of their respective APIs.

*TODO: consider these*
 - Would be difficult to refute ggvis - since it's got a more simpler API, and it's one of the few that does not do redrawing on plots + can do the trendline/slider challenge in more simpler steps, but cannot do the box plot example
- could mention that in Shiny, whenver they redraw, axes will automatically change. In `interactr` axes don't change, so it's a 'fair' comparison (however, if it requires changing, then we've got a limitation)

Because many of these existing tools are still being developed, it is likely that they may resolve these limitations in the future. However, some tools still require the user to be very familiar with its API. An example of this is the `plotly` package that has expanded further into achieving linking between other types of plots without the use of crosstalk or shiny and the ability to prevent redrawing when used with `shiny`.

## Future directions and further problems

The problem of handling large data sets is still present simply because the browser cannot handle too many SVG elements at once. A solution is to render using webGL and HTML canvas environments which allow for many elements to be rendered without compromising speed. However, the problem with this is that it is not as straightforward to attach events to thses elements as they are simply treated as a single element. 
 
There is potential in developing `interactr` further to try achieve more sophisticated interactions that are more useful in exploratory data analysis. Currently only a small number of examples have been successful. There is also a need for making it more simpler and versatile for users, but it could compromise the flexibility in which the user can define interactions. Possible ideas would include integrating plots with \textbf{D3} and other \textbf{htmlwidgets} to achieve special effects such as zooming and panning of a plot and to achieve multi-directional linking.
	