---
documentclass: report
fig_caption: yes
fontsize: 11pt
geometry: "left=3cm, right=3cm, top=3cm"
header-includes:
- \usepackage{amsmath}
- \usepackage{graphicx}
- \usepackage{framed}
- \usepackage{dsfont}
- \usepackage{float}
- \usepackage{caption}
- \usepackage{parskip}
- \usepackage{fancyhdr}
- \renewcommand{\topfraction}{0.85}
- \renewcommand{\textfraction}{0.1}
- \parindent=0cm
- \parskip=\baselineskip
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[RO,LE]{\thepage}
- \fancyhead[RE]{\itshape\leftmark}
- \fancyhead[LO]{\itshape\rightmark}
highlight: tango
linkcolor: black
output:
  pdf_document:
    number_sections: yes
    toc_depth: 3
    citation_package: natbib
urlcolor: blue
bibliography: bibliography.bib
---

<!-- this dissertation thesis was adapted from https://rosannavanhespenresearch.wordpress.com/2016/03/30/writing-your-thesis-with-r-markdown-5-the-thesis-layout/  -->

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'fig/',
                       warning = FALSE, message = FALSE,
                       out.width = "80%",
                       fig.align = "center", fig.pos = "H", out.extra = "")
```

\thispagestyle{empty}

```{r child = 'titlepage.Rmd'}
```
\pagenumbering{roman}
\cleardoublepage

```{r child = 'abstract.Rmd'}
```

\cleardoublepage

```{r child = 'exec-sum.Rmd'}
```

\cleardoublepage

```{r child = "ack.Rmd"}
```

\tableofcontents
\listoffigures

\cleardoublepage
\pagenumbering{arabic}

```{r child = 'chapter1.Rmd'}
```

\cleardoublepage

```{r child = 'chapter2.Rmd'}
```

\cleardoublepage

```{r child = 'chapter3.Rmd'}
```

\cleardoublepage

```{r child = 'chapter4.Rmd'}
```

\cleardoublepage

```{r child = 'chapter5.Rmd'}
```

# Bibliography
