---
title: animint
output: html_document
---

# Resources:
- 1 github repository: https://github.com/tdhock/animint + wiki page (look at this for more details about how it really works)
- 2 An academic paper describing how animint works: "Two new interactive keywords for interactive, animated plot design" - [link](https://www.google.co.nz/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiKy7rvvLPWAhWLbbwKHfSjBhoQFggmMAA&url=https%3A%2F%2Fraw.githubusercontent.com%2Ftdhock%2Fanimint-paper%2Fmaster%2FHOCKING-animint.pdf&usg=AFQjCNH8nZ9vDhPomdGzXHU5f_XFKkrE9w)
- 3 JCGS article (under review?)
- 4 [Tutorial](http://tdhock.github.io/animint/#introduction) page
- 5 [Designer manual](http://members.cbio.mines-paristech.fr/~thocking/animint-book/Ch00-preface.html)

*NOTE: when you install animint, it runs on CRAN version of ggplot2. To get back to crosstalk + plotly world (needs dev version of ggplot2), downgrade, then upgrade. Of course, you don't have to go through this if you're not using ggplotly!*

**Aim:** to design multi-plot, multi-layer interactive and animative data visualisations with ggplot2
- aesthetics are extended from ggplot2
- built and rendered using D3
- (2) 

**Background of interactive graphics and their definitions of 'interactive':**
- To deepen our understanding of multivariate data sets
- based upon the concept of 'direct manipulation'
- 'interactive': graphical elements are clicked to update data shown in plots
- Similar to dissertation - they've taken D3 as the starting point (points out that rCharts faces the same problem with 'no method of linking multiple plots') - D3 'allows visualisation to be specified using the DOM'
- Many htmlwidgets cannot produce interactive animations (the animation package - but based upon frames)
- focus is upon the grammar of graphics - mentioned ggplot2 + ggvis (shiny backend + Vega library - 'which does not directly support interactions + animations')
- covers iplots and cranvas briefly -  generally, only 1 data set can be explored at a single time

**Concept:**
- Based upon 2 simple aesthetics: clickSelects + showSelected
http://bl.ocks.org/tdhock/raw/217823c39eb1fc7c5dc9/
(2)
- clickSelects: clicking changes the current selection
- showSelected: shows data for current selection
- click directly on the SVG (so it's a direct on-plot interaction)


**Advantages:**
- can be incorporated into a shiny app
- SIMPLE API (lines of code are minimal, but they do lots of things + all plots LINK relatively smoothly + can be animated) - [climate example](http://members.cbio.mines-paristech.fr/~thocking/climate-anim/)
- compatible with RStudio tools: shiny, knitr/ interactive Rmd documents
- based upon grammar of graphics (popular for users)
- ggvis can't control both 'indirect' + 'direct' interactions at the same time (ie you cannot facilitate clicks on a plot)
    - the [closest](https://github.com/cpsievert/shiny_apps/blob/master/worldBank-ggvis/app.R) is hovers (which don't do anything) - [link](https://cpsievert.shinyapps.io/worldBank-ggvis/)
    - you can do simple animation (playback) + filtering, but not on-plot interactions (more focused on off-plot)
- Able to link between aggregated data + row-observational data
- Possibility of changing range axes between different sets of aggregated data
- can do BOTH animation + interaction!

**Disadvantages + Limitations:**
(3 - section 7)
- Everything is 'prerendered' (user cannot change variable mappings - they have to render a new plot if they want to change something)
- Not all ggplot2 features (some specific geoms) can be made interactive
- Only compatible with ggplot2 (framework uses it to compute data to be compiled and rendered)
- Subsets need to be computed before rendering (LARGE AMOUNT OF DATA TO BE STORED?)
- The downside with standalone: data-storage problem? (The TSVs a good idea since it doesn't overload the browser, but if you had so many different combinations, file sizes get big (78 MB for a large data set?))
- Direct manipulation limits: selecting graphical elements by clicking, showing and hiding elements (everything is either a click + show)
  - possible to hover + brushing (but not available)
  - other additions: zoom, pan, plot resize (...which is what I'm thinking if it's possible for gridSVG (with D3?) - both for use within DOM + standalone)

**Thoughts + takeaways**
- it's an interesting approach for trying to solve the problem we have with interactive graphics on the web
  - referred back to Cook and Swayne + the definition of direct manipulation
- simpler and more responsive approach for linking multiple plots together (it feels more smooth rather than using plotly + crosstalk/ plotly + ggvis)
- A simpler API! (there's a lot going under the hood (read their [compiler] + [renderer] articles!), but definitely more intuitive for developers) - might need pointers for end users? (but that's minor)
- relation back to data rather than elements on the page is something to consider (but it depends what kind of framework + underlying tools you're using)
- Could possibly implement a similar approach for a 'standalone' type/shareable using gridSVG + D3? (but will need a heck of a lot more JavaScript + R knowledge + might be beyond me. who knows.)
- setInterval in JS (for running animations?)
- The selectize.js library appears to be relatively popular for filtering/selecting (ie dropdown menus). Is it hard to implement/easy to use?
- This package has pretty good documentation + a whole lot of examples!

*argument against gridSVG?*
- grid objects referenced by name (which is what I'm doing!, but good point: needs to know naming :()
- the unfortunate side of ggplot2: it DOESN'T have a consistent name scheme.
- One of the major downfalls for gridSVG is actually the naming itself. It's good to name grobs, but finding out what's what is another problem within itself when you try match grid to gridSVG objects. (is there a way to get around this?)
