---
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    pandoc_args: [
      "--number-sections",
      "--number-offset=0"
    ]
bibliography: bibliography.bib
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.align = "center",
                      out.extra = "")
```

<br />

# Introduction

The purpose of this report is to investigate current solutions for creating web interactive data visualisations in R before designing a more flexible approach for customising interactions onto plots.

## The need for interactive graphics

Interactive graphics have become popular in helping users explore data freely and explain topics to a wider audience. As @murray13 suggests, static visualisations can only 'offer pre-composed 'views' of data', where as interactive plots can provide us with different perspectives. To be able to interact with a plot allows us to explore data, discover trends and relationships that cannot be seen with a static graph. The power of interactive graphics can aid us during exploratory data analysis, to which we can display and query data to answer specific questions the user has (@cosway07).

The term "interactive graphics" can have different meanings. Theus(1996) and Unwin(1999) have suggested that there are 3 broad components: querying, selection and linking, and varying plot characteristics. We can also split it into two broader categories - 'on-plot' and 'off-plot' interactivity. We focus on 'on-plot' interactivity, where a user can interact directly on the plot to query, select and explore the data.

R (@ihaka96) is a powerful open source tool for generating flexible static graphics. However, it is not focused on interactivity. Previously, there have been different programs to help create interactive plots to aid analysis including ggobi(Swayne et al, 2007), cranvas(Xie et al, 2013), iplots(Urbanek, 2007), and Mondrian(@theus02). Despite their capabilities, all these require installation of software which makes it difficult to share and reproduce results. More recently, new visualisation tools have begun to use the web browser to render plots and drive interactivity.

## The web and its main technologies

The web is an ideal platform for communicating and exchanging information in the present day. It has become accessible to everyone without the worries of device compatibility and installation. Web interactive visualisations are commonly used in areas including data journalism, informative dashboards for business analytics and decision making, and education. These will be continually demanded for in the future.

The main web technologies are HTML, CSS and JavaScript. Hyper Text Markup Language (known as HTML) is the language used to describe content on a webpage. Cascading style sheets (known as CSS) is the language that controls how elements look and are presented on a web page (such as color, shape, strokes and fills, borders). These can be used to define how specific types of elements are rendered on the page. JavaScript is the main programming language for the web, which is used to add interactivity to web pages. Whenever we interact with a website that has a button to click on or hover over text, these are driven by JavaScript.
The Document Object Model (known as the DOM) is the 'programming interface for HTML and XML documents' (MDN, 2017). A single web page can be considered as a document made up of nodes and objects with a certain structure. We can use the DOM to refer to specific elements, attributes and nodes on the page that we wish to modify and get information about using different programming languages, specifically JavaScript. This allows us to create and change a dynamic web page.

Application programming interfaces (APIs) are defined as 'a set of routines, protocols, and tools for building software applications' (MISSING REFERENCE). When we see a map from Google Maps embedded in a web page, that web page is calling the GoogleMaps API to provide the map. Through the context of this report, APIs generally refer to JavaScript libraries that are called upon and used to render plots.

Many interactive visuals on the web are generally rendered using Scalable Vector Graphics (known as SVG). This XML based format is widely used because it is easy to attach events and interactions to certain elements through the DOM. This cannot be done with a raster image, as a raster image (PNG or JPEG) is treated as an entire element.

## Motivational problem

The main motivation for this project stemmed upon whether there is a more intuitive way to generate simple interactive visuals from R without learning many tools. The solution could ideally be used to advance features in iNZight, a data visualisation software from the University of Auckland.

The approach is to identify and assess existing tools for creating web interactive visuals in R (Chapters 2 and 3) before building a viable solution (Chapter 4) that could potentially solve this problem.

# References {-}

**Note: currently just testing references and citations. Not all are referenced yet!**
