---
title: "Web interactive plots in R"
author: "Yu Han Soh"
---

This is the online interactive version of an [honours project report](dissertation.pdf).

A quick table of contents has been provided below.
Simply click on the tabs in the navigation bar (at the top of this page) to view
each section.

[Abstract](#abstract)  <br>
[Acknowledgements](#acknowledgements)  <br>
[1 Introduction](chapter1.html) <br>
[2 An overview of tools for achieving web interactive plots in R](chapter2.html)  <br>
[3 Interactive R plots using lower level tools](chapter3.html)  <br>
[4 Designing a more flexible way of producing simple interactions](chapter4.html) <br>
[5 Discussion](chapter5.html) <br>

References have been provided at the bottom of each section.

**NOTE:**
**Most of the examples have live links - simply click on the link and follow
the instructions. Some of them do take a while to load! Those that involve the
DOM package (Section 3.2 and all the examples from Section 4) only last for a few
minutes and require a strong internet connection. Once the text instructions
load, it is best to follow the instructions immediately.**

---

## Abstract {#abstract}

Web interactive graphics have become popular for sharing exploratory data
analysis. There are many approaches for creating web interactive
graphics, however, they are limited and do not allow users to customise and introduce
interactions that were not specifically planned for by these systems.
This report gives an overview of existing tools for creating web interactive
plots before developing and discussing a more flexible solution called **interactr**,
a prototype package that allows users to customise interactions on plots produced
in R and aims to remove the need for understanding how web technologies work.

---

## Acknowledgements {#acknowledgements}

Thank you to Dr. Paul Murrell for his technical expertise and witty analogies
that helped me understand the concepts and challenges of research and software
development. Thank you for being an inspirational role model to allow me to become
 a better programmer.

Thank you to Prof. Chris Wild for introducing me to the idea of interactive
graphics, for inspiring me to investigate further into this topic for iNZight
and for my own interests. Thank you for sharing ideas and challenging me further.

This project would not have been possible without their dedicated supervision
and support. I hope that it has helped them in their own research and inspires others
to have fun making their own interactive visuals in R.
